### ISSUE TITLE
Inconsistent with original

### ISSUE THREAD

**Issue by Heisenburger2020** [BEAM-Labs/ContraNovo#5]

**Comment by Heisenburger2020** [comment]
Dear Sir/Madam,
Why is contranovo encode peak different from the original paper?
![image](https://github.com/BEAM-Labs/ContraNovo/assets/65890878/79348072-0582-484f-b63d-35b0113c6011)
![a0cb58f426bbbf6204d9d584be5a352](https://github.com/BEAM-Labs/ContraNovo/assets/65890878/96260cec-d6a8-4164-9333-153bf902d0a0)

**Comment by kai-jz** [comment]
![image](https://github.com/BEAM-Labs/ContraNovo/assets/55545351/f95b83ad-8a53-4486-b9dd-532393108ef8)
Sorry, I don`t understand where is inconsistent. The massEncoder stratage is defined in massEncoder class as the figure.
